-- Your SQL goes here
CREATE TABLE IF NOT EXISTS habit_events (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	habit_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(habit_id) REFERENCES habits(id) ON DELETE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
)